---
title: "density"
author: "Sarah Urbut"
date: "2023-03-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,cache = FALSE,warning = FALSE,message = FALSE,message = FALSE,warning = FALSE)
```

## Introduction

Here we display the density of PRS and ASCVD 10 year Risk:

```{r}
library("ggridges")
source("code/utils.R")

df=readRDS("output/amit_df.rds")
df$agecat=cut(df$phenos.enrollment,breaks=c(0,55,65,100),labels=c("<55","55-65",">65"))

prs=ggplot(df, aes(x = prs_quant, y = agecat,fill=agecat)) + 
  geom_density_ridges() + theme_ridges()+labs(x = "Genomic Risk Quantile", y = "Density",fill="Age Category")+scale_fill_futurama()+theme_classic()

prs

df$prscat=factor(df$prscat,levels = c("low","intermediate","high"),labels=c("<20%","20-80%",">80%"))

age=ggplot(df, aes(x = phenos.enrollment, y = prscat,fill=prscat)) + 
  geom_density_ridges() + theme_ridges()+labs(x = "Age of Enrollment", y = "Density",fill="PRS Category")+scale_fill_jama()+theme_classic()

age

```

```{r}
ggsave(prs,filename = "Figs/density/prs_distribution.tiff",width = 6,height = 3,dpi=300)
ggsave(age,filename = "Figs/density/age_distribution.tiff",width = 6,height = 3,dpi=300)
```

```{r}

pce=ggplot(df, aes(x = ascvd_10y_accaha_all, y = agecat,fill=agecat)) + 
  geom_density_ridges() + theme_ridges()+labs(x = "Predicted 10-year ASCVD Percentile ", y = "Density",fill="Age Category")+scale_fill_futurama()+xlim(0,40)+theme_classic()

pce
```

```{r}
ggsave(pce,filename = "Figs/density/pce_distribution.tiff",width = 6,height = 3,dpi=300)
```


