---
title: "Fig1"
author: "Sarah Urbut"
date: "2023-03-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,cache = FALSE,warning = FALSE,message = FALSE)

```

```{r,echo=F,message=FALSE}
library("dplyr")
library("tidyverse")
library("survival")
library("survminer")
library("eulerr")
library("ggplot2")
library("reshape")
library("ggfortify")
library("gridExtra")
library("survMisc")
library("rsq")
library("pROC")
library("data.table")
library("RColorBrewer")
library("gt")
library("DT")
library(plotly)
library(dplyr)
library(carData)
library(gapminder)
library(babynames)
```

## HR for UKB



```{r chunkenew}
df=readRDS("output/amit_df.rds")
dat=data.frame(df %>%group_by(round(phenos.enrollment,0)) %>%summarise(length(phenos.enrollment)))[c(3:32),]


hazards=data.frame(readRDS("output/hazards_rate_UKB_amit.rds"))
upperbound=data.frame(readRDS("output/hazards_rate_upperbound_amit.rds"))
lowerbound=data.frame(readRDS("output/hazards_rate_lowerbound_amit.rds"))


hrmat=hazards[,grep("HR",colnames(hazards))];
hrmat$age=dat$round.phenos.enrollment..0.

ormat=hazards[,grep("OR",colnames(hazards))];ormat$age=dat$round.phenos.enrollment..0.
r2mat=hazards[,grep("r2",colnames(hazards))];r2mat$age=dat$round.phenos.enrollment..0.

colnames(hrmat)=colnames(ormat)=colnames(r2mat)=c("Polygenic score","Pooled cohort equations","LDL Cholesterol","Smoking","Age","Systolic blood pressure","Diabetes mellitus","Body Mass Index","Male Sex","High-density lipoprotein","Total cholesterol","age")


upperbound$age=dat$round.phenos.enrollment..0.
u=melt(upperbound,id.vars="age")

lowerbound$age=dat$round.phenos.enrollment..0.
l=melt(lowerbound,id.vars="age")


```

```{r}
## convert to longform
library(RColorBrewer)
haz = melt(hrmat, id.vars = "age")
ors = melt(ormat, id.vars = "age")
r2s = melt(r2mat, id.vars = "age")

haz$low.se = l$value
haz$upper.se = u$value




col_pce <- rev(brewer.pal(10, "Paired"))
col_p = c(col_pce[1:3],
          col_pce[5],
          col_pce[4],
          col_pce[c(6, 10)],
          "black",
          col_pce[9],
          "turquoise",
          col_pce[7])

r2s$variable = ors$variable = haz$variable <-
  factor(
    haz$variable,
    levels = c(
      "Diabetes mellitus",
      "Male Sex",
      "Smoking",
      "Polygenic score",
      "LDL Cholesterol",
      "Systolic blood pressure",
      "Body Mass Index",
      "Pooled cohort equations",
      "Age",
      "High-density lipoprotein",
      "Total cholesterol"
    )
  )



hr_ukb_all = ggplot(subset(
  haz,
  variable %in% c(
    "Diabetes mellitus",
    "Smoking",
    #"Male Sex",
    "Polygenic score",
    "High-density lipoprotein",
    "Systolic blood pressure",
    #"Age",
    "Total cholesterol"
  )
),
aes(age, value, colour = variable)) +
  labs(y = "Hazard Ratio of Coronary Artery Disease", x = "Age of Risk Assessment", colour =
         "Risk Factor") +
  geom_point(size = 1) +
  stat_smooth(method = "loess", span = 1) +
  scale_color_manual(
    values = col_p,
    drop = TRUE,
    breaks = c(
      "Diabetes mellitus",
      "Male Sex",
      "Smoking",
      "Polygenic score",
      "LDL Cholesterol",
      "Systolic blood pressure",
      "Body Mass Index",
      "Pooled cohort equations",
      "Age",
      "High-density lipoprotein",
      "Total cholesterol"
    )
  )





r2_ukb_all = ggplot(subset(
  r2s,
  variable %in% c(
    "Diabetes mellitus",
    "Smoking",
    "Polygenic score",
    #"Male Sex",
    "High-density lipoprotein",
    "Systolic blood pressure",
    #"Age",
    "Total cholesterol"
  )
),
aes(age, value, colour = variable)) +
  labs(y = "Proportion of Variation Explained", x = "Age of Risk Assessment", colour =
         "Risk Factor") +
  geom_point(size = 1) +
  stat_smooth(method = "loess", span = 1) +
  scale_color_manual(
    values = col_p,
    drop = TRUE,
    breaks = c(
      "Diabetes mellitus",
      "Male Sex",
      "Smoking",
      "Polygenic score",
      "LDL Cholesterol",
      "Systolic blood pressure",
      "Body Mass Index",
      "Pooled cohort equations",
      "Age",
      "High-density lipoprotein",
      "Total cholesterol"
    )
  )




tgt = c("Diabetes mellitus", "Smoking", "Polygenic score", "Systolic blood pressure","High-density lipoprotein", "Total cholesterol")

dat = haz %>% filter(variable %in% tgt)
datr = r2s %>%filter(variable %in% tgt)

hr_ukb_all = dat %>%
  ggplot(aes(x = age, y = value, colour = variable, fill = variable
             )) +
  geom_point(size = 1) +
  stat_smooth(method = "loess", span = 1) +
  scale_color_manual(values=col_p, drop=TRUE,breaks=c("Diabetes mellitus","Male Sex","Smoking","Polygenic score","LDL Cholesterol","Systolic blood pressure","Body Mass Index","Pooled cohort equations","Age","High-density lipoprotein","Total cholesterol")) +
   scale_fill_manual(values=col_p, drop=TRUE, breaks=c("Diabetes mellitus","Male Sex","Smoking","Polygenic score","LDL Cholesterol","Systolic blood pressure","Body Mass Index","Pooled cohort equations","Age","High-density lipoprotein","Total cholesterol"))+
  labs(y = "Hazard Ratio of Coronary Artery Disease", x = "Age of Risk Assessment", colour = "Risk Factor")

# 
  
  
r2_ukb_all = datr %>%
  ggplot(aes(x = age, y = round(value,2), colour = variable,fill = variable
             )) +
  geom_point(size = 1) +
  stat_smooth(method = "loess", span = 1) +
  scale_color_manual(values=col_p, drop=TRUE,breaks=c("Diabetes mellitus","Male Sex","Smoking","Polygenic score","LDL Cholesterol","Systolic blood pressure","Body Mass Index","Pooled cohort equations","Age","High-density lipoprotein","Total cholesterol")) +
   scale_fill_manual(values=col_p, drop=TRUE, breaks=c("Diabetes mellitus","Male Sex","Smoking","Polygenic score","LDL Cholesterol","Systolic blood pressure","Body Mass Index","Pooled cohort equations","Age","High-density lipoprotein","Total cholesterol"))+
  labs(y = "Proportion of Variation Explained", x = "Age of Risk Assessment", colour = "Risk Factor")

# 
  
## formatting
source("code/utils.R")

r2 = r2_ukb_all + theme_classic(base_size = 20) + theme(legend.position = "none") +
  tems+ylim(0,0.18)

hall = hr_ukb_all + theme_classic(base_size = 20) + tems 
## generate without legend
hr_ukb_all_nolegend=hr_ukb_all+theme_classic(base_size = 20)+theme(legend.position = "none")+ylim(c(0.35,5)) 

```

## ALL

```{r}
ggplotly(hall)
```


```{r}
ggplotly(r2)
```

## Save figures

```{r}
fig_path="./Figs/Fig1/"
ggsave(hall,filename = paste0(fig_path,"hr_ukb_leg.tiff"),dpi = 300,width = 6,height = 6)
ggsave(hr_ukb_all_nolegend,filename = paste0(fig_path,"hr_ukb_all_noleg.tiff"),dpi = 300,width = 6,height = 6)
ggsave(r2,filename = paste0(fig_path,"r2_ukb_all.tiff"),dpi=300,width=6,height=6)
```


## Now for just PCE

```{r}


hr_ukb_pce = ggplot(subset(
  haz,
  variable %in% c("Pooled cohort equations")
),
aes(age, value, colour = variable)) +
  labs(y = "Hazard Ratio of Coronary Artery Disease", x = "Age of Risk Assessment", colour =
         "Risk Factor") +
  geom_point(size = 0.5) +
  stat_smooth(method = "loess", span = 1) +
  scale_color_manual(
    values = col_p,
    drop = TRUE,
    breaks = c(
      "Diabetes mellitus",
      "Male Sex",
      "Smoking",
      "Polygenic score",
      "LDL Cholesterol",
      "Systolic blood pressure",
      "Body Mass Index",
      "Pooled cohort equations",
      "Age",
      "High-density lipoprotein",
      "Total cholesterol"
    )
  )





r2_ukb_pce = ggplot(subset(
  r2s,
  variable %in% c("Pooled cohort equations"
  )
),
aes(age, value, colour = variable)) +
  labs(y = "Proportion of Variation Explained", x = "Age of Risk Assessment", colour =
         "Risk Factor") +
  geom_point(size = 0.5) +
  stat_smooth(method = "loess", span = 1) +
  scale_color_manual(
    values = col_p,
    drop = TRUE,
    breaks = c(
      "Diabetes mellitus",
      "Male Sex",
      "Smoking",
      "Polygenic score",
      "LDL Cholesterol",
      "Systolic blood pressure",
      "Body Mass Index",
      "Pooled cohort equations",
      "Age",
      "High-density lipoprotein",
      "Total cholesterol"
    )
  )

r2_pce = r2_ukb_pce + theme_classic(base_size = 20)+theme(legend.position = "none")+ylim(0,0.15)
#hall_pce = hr_ukb_pce + theme_classic(base_size = 20) + tems +ylim(0.8,4.5)
hall_pce = hr_ukb_pce + theme_classic(base_size = 20) + tems +ylim(0.8,2)+theme(legend.position = "none")
```

```{r}
ggsave(hall_pce,filename = paste0(fig_path,"hr_pce.tiff"),dpi = 300,width = 6,height = 6)
ggsave(r2_pce,filename = paste0(fig_path,"r2_pce.tiff"),dpi = 300,width = 6,height = 6)
```

```{r}
ggplotly(hall_pce)
```

```{r}
ggplotly(r2_pce)
```

## Hazard Rate Lookup Table
```{r}
library(DT)
m=cbind(haz[,c(1:2)],round(haz[,c(3:5)],2))
colnames(m)=colnames(haz)
DT::datatable(m)
```

## Proportion Variation Explained Lookup Table

```{r}
library(DT)
m=cbind(r2s[,c(1:2)],round(r2s[,c(3)],2))
colnames(m)=colnames(r2s)
DT::datatable(m)
```
