---
title: "Fig3"
author: "Sarah Urbut"
date: "2023-03-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,cache = FALSE,warning = FALSE,message = FALSE,fig.path = "./Figs/")

```

## Resolution increases

Here we stratify by PRS and by ASCVD to show folks that are captured by PRS but not by PCE. Critically, for these younger folks CAC offers little NPV for restratification under existing means.

```{r,message=FALSE,eval=TRUE}
library(ggplot2)
library(plotly)
df=readRDS("output/amit_df.rds")
df$chd=df$phenos.has_CAD
df=na.omit(df)
df$round_age=round(df$phenos.enrollment,0)
df$round_age=as.factor(df$round_age)
df$ldl.quant=scale(df$ldladj)
df$sbp.quant=scale(df$sbp)
df$hdl.quant=scale(df$hdladj)
df$chol.quant=scale(df$choladj)
library("ggsci")
library("ggplot2")
library("gridExtra")
library("RColorBrewer")
library(dplyr)
library(tidyr)


df$ascvdcat_all <- cut(df$ascvd_10y_accaha_all, breaks=c(0, 7.5, 20,Inf), labels=c("low", "intermediate","high"))
#df$prscat <- cut(df$prs.r, breaks=c(0, 0.20,0.80,0.975,1), labels=c("low", "intermediate","int-high","high"))

df$prscat <- cut(df$prs.r, breaks=c(0, 0.20,0.80,1), labels=c("low", "intermediate","high"))



mat=array(NA,dim=c(length(levels(df$ascvdcat_all)),length(levels(df$prscat)),6))
num=array(NA,dim=c(length(levels(df$ascvdcat_all)),length(levels(df$prscat)),6))
se=array(NA,dim=c(length(levels(df$ascvdcat_all)),length(levels(df$prscat)),6))

df=na.omit(df)
agelist=c(40,45,50,55,60,65,70)

colnames(mat)=colnames(se)=levels(df$prscat)
rownames(mat)=colnames(se)=levels(df$ascvdcat_all)

for(i in 1:length(levels(df$ascvdcat_all))){
  a=levels(df$ascvdcat_all)[i]
  for(j in 1:length(levels(df$prscat))){
    for(g in 1:length(agelist)-1){
      p=levels(df$prscat)[j]
      #print(c(a,p))
      good=df[which(df$ascvdcat_all==a&df$prscat==p&df$phenos.enrollment<=agelist[g+1]&df$phenos.enrollment>=agelist[g]),]
      phat=mean(good$phenos.has_CAD==1)
      q=1-phat
      n=sum(good$phenos.has_CAD==1)
      l=nrow(good)
      mat[i,j,g]=phat
      num[i,j,g]=n
      se[i,j,g]=sqrt((phat*q)/l)
    }
  }}


a=mat[,,1]
s=se[,,1]
sa <- stack(as.data.frame(mat[,,1]))
sea <- stack(as.data.frame(se[,,1]))
sea$PCE_cat=sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
colgrad=c("#79AF97FF","#00A1D5FF","#B24745FF")
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa$upper=sa$values+sea$values
sa$lower=sa$values-sea$values
sa1 = sa
sa1$age = "40-45"


# sa %>% ggplot(aes(x=interaction(age, PCE_cat), y=values, color=factor(ind), size=values)) + geom_point(size=3)+labs(x = "ASCVD-Risk: PCE ",title="Abs Risk by PRS-PCE Category",y="Absolute Risk",colour="PRS_cat")+theme_classic()+scale_color_manual(values = c(r[c(3,5,4)]))+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
# sa1=sa


a=mat[,,2]
s=se[,,2]
sa <- stack(as.data.frame(mat[,,2]))
sea <- stack(as.data.frame(se[,,2]))
sea$PCE_cat=sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
colgrad=c("#79AF97FF","#00A1D5FF","#B24745FF")
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa$upper=sa$values+sea$values
sa$lower=sa$values-sea$values
sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa2=sa
sa2$age = "45-50"


# sa %>% ggplot(aes(x=interaction(age, PCE_cat), y=values, color=factor(ind), shape=factor(age))) + geom_point(size=3)+labs(x = "ASCVD-Risk: PCE ",title="Abs Risk by PRS-PCE Category",y="Absolute Risk",colour="PRS_cat")+theme_classic()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+scale_color_manual(values = colgrad)


sa <- stack(as.data.frame(mat[,,3]))
s=se[,,3]
sa <- stack(as.data.frame(mat[,,3]))
sea <- stack(as.data.frame(se[,,3]))

sea$PCE_cat=sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
colgrad=c("#79AF97FF","#00A1D5FF","#B24745FF")
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa$upper=sa$values+sea$values
sa$lower=sa$values-sea$values

sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa3=sa
sa3$age = "50-55"


sa <- stack(as.data.frame(mat[,,4]))

s=se[,,4]
sa <- stack(as.data.frame(mat[,,4]))
sea <- stack(as.data.frame(se[,,4]))

sea$PCE_cat=sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
colgrad=c("#79AF97FF","#00A1D5FF","#B24745FF")
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa$upper=sa$values+sea$values
sa$lower=sa$values-sea$values

sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa4=sa
sa4$age = "55-60"
sa=sa4
# sa %>% ggplot(aes(x=interaction(age, PCE_cat), y=values, color=factor(ind), shape=factor(age))) + geom_point(size=3)+labs(x = "ASCVD-Risk: PCE ",title="Abs Risk by PRS-PCE Category",y="Absolute Risk",colour="PRS_cat")+theme_classic()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+scale_color_manual(values = colgrad)

sa <- stack(as.data.frame(mat[,,5]))

s=se[,,5]
sa <- stack(as.data.frame(mat[,,5]))
sea <- stack(as.data.frame(se[,,5]))

sea$PCE_cat=sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
colgrad=c("#79AF97FF","#00A1D5FF","#B24745FF")
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa$upper=sa$values+sea$values
sa$lower=sa$values-sea$values

sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa5=sa
sa5$age = "60-65"
sa=sa5

# sa %>% ggplot(aes(x=interaction(age, PCE_cat), y=values, color=factor(ind), shape=factor(age))) + geom_point(size=3)+labs(x = "ASCVD-Risk: PCE ",title="Abs Risk by PRS-PCE Category",y="Absolute Risk",colour="PRS_cat")+theme_classic()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+scale_color_manual(values = colgrad)

sa <- stack(as.data.frame(mat[,,6]))

s=se[,,6]
sa <- stack(as.data.frame(mat[,,6]))
sea <- stack(as.data.frame(se[,,6]))

sea$PCE_cat=sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
colgrad=c("#79AF97FF","#00A1D5FF","#B24745FF")
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa$upper=sa$values+sea$values
sa$lower=sa$values-sea$values

sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
sa6=sa
sa6$age = "65-70"
sa=sa6


# sa %>% ggplot(aes(x=interaction(age, PCE_cat), y=values, color=factor(ind), shape=factor(age))) + geom_point(size=3)+labs(x = "ASCVD-Risk: PCE ",title="Abs Risk by PRS-PCE Category",y="Absolute Risk",colour="PRS_cat")+ theme_classic()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+scale_color_manual(values = colgrad)



# sa <- stack(as.data.frame(mat[,,7]))
# sa$PCE_cat <- rep(c("0-7.5","7.5-20","20-100"), ncol(a))
# sa$PCE_cat=factor(sa$PCE_cat,levels = c("0-7.5","7.5-20","20-100"))
# sa7=sa
# sa7$age = "70-75"
# sa=sa7
```

```{r}
sa = rbind(sa2,sa3,sa4,sa5,sa6)

#sa = rbind(sa1, sa2,sa3)  
b=rev(brewer.pal(n = 8, name = "RdBu")[1:3])

p=sa %>% ggplot(aes(x=interaction(age,PCE_cat), y=values,ymin = lower, ymax =upper,color=ind)) + geom_point(size=3)+labs(x = "Age and ASCVD-Risk",title="Absolute Risk by PRS-PCE Category",y="Absolute Risk",colour="PRS Category")+scale_color_manual(values = colgrad)+theme_classic(base_size = 20)+geom_errorbar(width = 0.2)+scale_x_discrete("Age at Risk Estimation",labels = rep(c("45-50","50-55","55-60","60-65","65-70"),3))+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# p=p+theme(axis.text.x=element_blank(), #remove x axis labels
#         axis.ticks.x=element_blank(), #remove x axis ticks
#         axis.text.y=element_blank(),  #remove y axis labels
#         axis.ticks.y=element_blank()  #remove y axis ticks
#         )
ggsave(p,filename = "Figs/Fig3/interaction.tiff",dpi=300,height = 5,width=8)
ggplotly(p)
```

