---
title: "Supp_ASCVD"
author: "Sarah Urbut"
date: "2023-03-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,cache = FALSE,warning = FALSE,message = FALSE)

```


```{r mergedbar}
source("code/utils.R")

df=data.frame(readRDS("output/amit_df.rds"))
df$chd=df$phenos.has_CAD


df$AGE1=df$phenos.enrollment

# m=rbind(df[,c("AGE1","prs.r","ascvd_10y_accaha","chd")],dff[,c("AGE1","prs.r","ascvd_10y_accaha","chd")])
# 
# df=m
# df=df[df$AGE1>=40&df$AGE1<=70,]

library(scales)
hex <- hue_pal()(6)


i=df %>% mutate(ints=cut(AGE1,breaks=c(39.99,45,50,55,60,65,70,75)))
i=i[!is.na(i$ints),]
fulla=i%>%group_by(ints)%>%summarise("Low"=mean(ascvd_10y_accaha_all<7.5),"Intermediate"=mean(ascvd_10y_accaha_all>7.5&ascvd_10y_accaha_all<20),"High"=mean(ascvd_10y_accaha_all>20),"n"=length(ints))
# 
errors=sqrt(fulla[,c(2:4)]*(1-fulla[,c(2:4)])/fulla$n)
errors=cbind("ints"=fulla$ints,errors)
colnames(errors)=colnames(fulla)[1:4]
hex <- c("green","orange","red")
# 
# mat=as.matrix(fulla[,c(2:3)])*100
# 
# barplot(t(mat),beside = T,names=fulla$ints,legend=F,col=c(hex[c(1,3)]),main="FHS+UKB Incident Cases Correctly Predicted",ylab="Proportion of Incident Cases Correctly Predicted",las=2)
# legend("topleft",legend=c("PRS only","PCE only"),fill =c(hex[c(1,3)]))
# 
r=melt(data.frame(fulla[,c(1,2,4,3)]),id.vars = "ints")
s=melt(data.frame(errors),id.vars = "ints")



r$lower=r$value-s$value
r$upper=r$value+s$value
names(r)[2]="ASCVD 10 year-Risk"
r$`ASCVD 10 year-Risk`=factor(r$`ASCVD 10 year-Risk`,levels=c("Low","Intermediate","High"),labels=c("<7.5","7.5-20",">20"))
p <- ggplot(data=r, aes(x=ints, y = value,fill = `ASCVD 10 year-Risk`)) + geom_bar(stat="identity") +labs(y = "Proportion of People",x="Age at Risk Estimation")+scale_fill_manual(values=c("#00b159","#f37735","#d11141"))+theme_classic(base_size = 25)+tems#+geom_errorbar(aes(ymin = value-error, ymax = value+error), width = 0.3, position = "identity")




ggplot2::ggsave(p,filename = "Figs/Supplemental/proportion_plots_ascvd.tiff",dpi = 300,height = 5,width = 8)

write.table(r,"output/proportions_table_ascvd.csv",sep=",",row.names = F,quote=F)
```

```{r}
ggplotly(p)
```

```{r}
library(DT)
m=cbind(r[,c(1:2)],round(r[,c(3:5)],2))
colnames(m)=colnames(r)
DT::datatable(m)
```
